version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 3m
  issues-exit-code: 1

linters-settings:
  staticcheck:
    checks:
      - all
      - -ST1000
      - -ST1003
      - -ST1016
